ALTER TABLE cliente ADD COLUMN consentimento_lgpd BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cliente ADD COLUMN data_consentimento TIMESTAMP WITH TIME ZONE;
ALTER TABLE cliente ADD COLUMN anonimizado BOOLEAN NOT NULL DEFAULT FALSE;
